let mySprite = sprites.create(img`
    ................
    ................
    .eeee....eeee...
    .edde....edde...
    .edeeeeeeeede...
    .eeeefeefeeee...
    ...eefeefee.....
    ...eeeeeeee.....
    ...eedffdee.....
    ...eeddddee.....
    ...eeeeeeee.....
    ................
    .ee.eeeeee..ee..
    .ee.eeddee..ee..
    .ee.eeddee..ee..
    ....eeddee......
    ....eeddee......
    ....eeddee......
    ................
    ....ee..ee......
    ....ee..ee......
    `, SpriteKind.Player)
tiles.setCurrentTilemap(tilemap`level1`)
controller.moveSprite(mySprite)
scene.cameraFollowSprite(mySprite)
